server:
  port: 8090
  connection-timeout: 6000     
spring:
  messages:
    basename: i18n/index
  datasource:
    #url: jdbc:sqlserver://localhost:1433;databaseName=Horadada
    url: jdbc:oracle:thin:@iqpc-003:1521:Horadada
    username: horadada
    password: aponte17
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.Oracle10gDialect
    show-sql: true 
    hibernate:
      ddl-auto: update
      naming:
        #strategy: org.hibernate.cfg.ImprovedNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        
        #mvn install:install-file -Dfile=C:\\app\\alexander\\product\\11.2.0\\dbhome_1\\jdbc\\lib\\ojdbc6.jar -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=11.2.0 -Dpackaging=jar
        #https://es.stackoverflow.com/questions/65317/como-instalar-maven-en-windows