package com.projecto.Horadada.Entity;
// Generated 12-may-2018 11:30:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="CLIENTE"
    ,schema="HORADADA"
)
public class Cliente  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcliente;
     private String ruc;
     private String razonsocial;
     private String direccionfiscal;
     private String telefono;
     private String correo;
     private Set<Despacho> despachos = new HashSet<Despacho>(0);
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Contacto> contactos = new HashSet<Contacto>(0);
     private Set<Valorizacion> valorizacions = new HashSet<Valorizacion>(0);
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Cliente() {
    }

	
    public Cliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public Cliente(int idcliente, String ruc, String razonsocial, Set<Despacho> despachos, Set<Factura> facturas, Set<Contacto> contactos, Set<Valorizacion> valorizacions, Set<Solicitud> solicituds,String direccionfiscal,String telefono,String correo) {
       this.idcliente = idcliente;
       this.ruc = ruc;
       this.razonsocial = razonsocial;
       this.despachos = despachos;
       this.facturas = facturas;
       this.contactos = contactos;
       this.valorizacions = valorizacions;
       this.solicituds = solicituds;
       this.direccionfiscal = direccionfiscal;
       this.telefono = telefono;
       this.correo = correo;
    }
   
     @Id 	
    @GeneratedValue(strategy=GenerationType.SEQUENCE , generator = "cliente_seq") @SequenceGenerator (	
                    name = "cliente_seq" ,	
                    sequenceName = "cliente_sequence" ,	
                    allocationSize = 1 )
    
    @Column(name="IDCLIENTE", unique=true, nullable=false, precision=10, scale=0)
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }

    
    @Column(name="RUC", length=11)
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    
    @Column(name="RAZONSOCIAL", length=25)
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }


@OneToMany(fetch=FetchType.EAGER, mappedBy="cliente")
    public Set<Despacho> getDespachos() {
        return this.despachos;
    }
    
    public void setDespachos(Set<Despacho> despachos) {
        this.despachos = despachos;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="cliente")
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="cliente")
    public Set<Contacto> getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set<Contacto> contactos) {
        this.contactos = contactos;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="cliente")
    public Set<Valorizacion> getValorizacions() {
        return this.valorizacions;
    }
    
    public void setValorizacions(Set<Valorizacion> valorizacions) {
        this.valorizacions = valorizacions;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="cliente")
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }

    @Column(name="DIRECCIONFISCAL", length=40)
	public String getDireccionfiscal() {
		return direccionfiscal;
	}


	public void setDireccionfiscal(String direccionfiscal) {
		this.direccionfiscal = direccionfiscal;
	}

	@Column(name="TELEFONO", length=40)
	public String getTelefono() {
		return telefono;
	}


	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name="CORREO", length=605)
	public String getCorreo() {
		return correo;
	}


	public void setCorreo(String correo) {
		this.correo = correo;
	}




}


