package com.projecto.Horadada.Entity;
// Generated 12-may-2018 11:30:17 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name="CONTACTO"
    ,schema="HORADADA"
)
public class Contacto  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcontacto;
     private Cliente cliente;
     private Persona persona;
     private Date fechacreacion;

    public Contacto() {
    }

	
    public Contacto(int idcontacto, Date fechacreacion) {
        this.idcontacto = idcontacto;
        this.fechacreacion = fechacreacion;
    }
    public Contacto(int idcontacto, Cliente cliente, Persona persona, Date fechacreacion) {
       this.idcontacto = idcontacto;
       this.cliente = cliente;
       this.persona = persona;
       this.fechacreacion = fechacreacion;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE , generator = "contacto_seq") @SequenceGenerator (    			
             name = "contacto_seq" ,
             sequenceName = "contacto_seq" ,
             allocationSize = 1 )
    
    @Column(name="IDCONTACTO", unique=true, nullable=false, precision=10, scale=0)
    public int getIdcontacto() {
        return this.idcontacto;
    }
    
    public void setIdcontacto(int idcontacto) {
        this.idcontacto = idcontacto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDCLIENTE")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDPERSONA")
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHACREACION", nullable=false, length=7)
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }




}


