package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Cotizacion generated by hbm2java
 */
@Entity
@Table(name="COTIZACION"
    ,schema="HORADADA"
)
public class Cotizacion  implements Serializable {


     private int idcotizacion;
     private Solicitud solicitud;
     private Date fechaenvio;
     private BigDecimal subtotal;
     private BigDecimal descuentos;
     private BigDecimal neto;
     private BigDecimal igv;
     private BigDecimal percepcion;
     private BigDecimal total;
     private int idmoneda;
     private String observaciones;
     private BigDecimal cargos;
     private Set<Cotizaciondetalle> cotizaciondetalles = new HashSet<Cotizaciondetalle>(0);
     private Set<Ordencompra> ordencompras = new HashSet<Ordencompra>(0);

    public Cotizacion() {
    }

	
    public Cotizacion(int idcotizacion) {
        this.idcotizacion = idcotizacion;
    }
    public Cotizacion(int idcotizacion, Solicitud solicitud, Date fechaenvio, BigDecimal subtotal, BigDecimal descuentos, BigDecimal neto, BigDecimal igv, BigDecimal percepcion, BigDecimal total, int idmoneda, String observaciones, BigDecimal cargos, Set<Cotizaciondetalle> cotizaciondetalles, Set<Ordencompra> ordencompras) {
       this.idcotizacion = idcotizacion;
       this.solicitud = solicitud;
       this.fechaenvio = fechaenvio;
       this.subtotal = subtotal;
       this.descuentos = descuentos;
       this.neto = neto;
       this.igv = igv;
       this.percepcion = percepcion;
       this.total = total;
       this.idmoneda = idmoneda;
       this.observaciones = observaciones;
       this.cargos = cargos;
       this.cotizaciondetalles = cotizaciondetalles;
       this.ordencompras = ordencompras;
    }
   
     @Id 

    
    @Column(name="IDCOTIZACION", unique=true, nullable=false, precision=10, scale=0)
    public int getIdcotizacion() {
        return this.idcotizacion;
    }
    
    public void setIdcotizacion(int idcotizacion) {
        this.idcotizacion = idcotizacion;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDSOLICITUD")
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }

    @DateTimeFormat(pattern = "dd/MM/yyyy")
    @Temporal(TemporalType.DATE)
    @Column(name="FECHAENVIO", length=7)
    public Date getFechaenvio() {
        return this.fechaenvio;
    }
    
    public void setFechaenvio(Date fechaenvio) {
        this.fechaenvio = fechaenvio;
    }

    
    @Column(name="SUBTOTAL", precision=9)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="DESCUENTOS", precision=9)
    public BigDecimal getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(BigDecimal descuentos) {
        this.descuentos = descuentos;
    }

    
    @Column(name="NETO", precision=9)
    public BigDecimal getNeto() {
        return this.neto;
    }
    
    public void setNeto(BigDecimal neto) {
        this.neto = neto;
    }

    
    @Column(name="IGV", precision=9)
    public BigDecimal getIgv() {
        return this.igv;
    }
    
    public void setIgv(BigDecimal igv) {
        this.igv = igv;
    }

    
    @Column(name="PERCEPCION", precision=9)
    public BigDecimal getPercepcion() {
        return this.percepcion;
    }
    
    public void setPercepcion(BigDecimal percepcion) {
        this.percepcion = percepcion;
    }

    
    @Column(name="TOTAL", precision=9)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    
    @Column(name="IDMONEDA", precision=10, scale=0)
    public int getIdmoneda() {
        return this.idmoneda;
    }
    
    public void setIdmoneda(int idmoneda) {
        this.idmoneda = idmoneda;
    }

    
    @Column(name="OBSERVACIONES", length=250)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="CARGOS", precision=9)
    public BigDecimal getCargos() {
        return this.cargos;
    }
    
    public void setCargos(BigDecimal cargos) {
        this.cargos = cargos;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="cotizacion")
    public Set<Cotizaciondetalle> getCotizaciondetalles() {
        return this.cotizaciondetalles;
    }
    
    public void setCotizaciondetalles(Set<Cotizaciondetalle> cotizaciondetalles) {
        this.cotizaciondetalles = cotizaciondetalles;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="cotizacion")
    public Set<Ordencompra> getOrdencompras() {
        return this.ordencompras;
    }
    
    public void setOrdencompras(Set<Ordencompra> ordencompras) {
        this.ordencompras = ordencompras;
    }

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;


}


