package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CotizaciondetalleId generated by hbm2java
 */
@Embeddable
public class CotizaciondetalleId  implements java.io.Serializable {


     private long idcotizaciondetalle;
     private long idcotizacion;

    public CotizaciondetalleId() {
    }

    public CotizaciondetalleId(long idcotizaciondetalle, long idcotizacion) {
       this.idcotizaciondetalle = idcotizaciondetalle;
       this.idcotizacion = idcotizacion;
    }
   


    @Column(name="IDCOTIZACIONDETALLE", nullable=false, precision=10, scale=0)
    public long getIdcotizaciondetalle() {
        return this.idcotizaciondetalle;
    }
    
    public void setIdcotizaciondetalle(long idcotizaciondetalle) {
        this.idcotizaciondetalle = idcotizaciondetalle;
    }


    @Column(name="IDCOTIZACION", nullable=false, precision=10, scale=0)
    public long getIdcotizacion() {
        return this.idcotizacion;
    }
    
    public void setIdcotizacion(long idcotizacion) {
        this.idcotizacion = idcotizacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CotizaciondetalleId) ) return false;
		 CotizaciondetalleId castOther = ( CotizaciondetalleId ) other; 
         
		 return (this.getIdcotizaciondetalle()==castOther.getIdcotizaciondetalle())
 && (this.getIdcotizacion()==castOther.getIdcotizacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdcotizaciondetalle();
         result = 37 * result + (int) this.getIdcotizacion();
         return result;
   }   


}


