package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cotizacion generated by hbm2java
 */
@Entity
@Table(name = "cotizacion", schema = "dbo", catalog = "HORADADA")
public class Cotizacion implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private int idCotizacion;
	private Solicitud solicitud;
	private Integer aprobado;
	private BigDecimal cargos;
	private BigDecimal descuentos;
	private Date fechaEnvio;
	private Integer idMoneda;
	private BigDecimal igv;
	private BigDecimal neto;
	private String observaciones;
	private BigDecimal percepcion;
	private BigDecimal subTotal;
	private BigDecimal total;
	private List<CotizacionDetalle> cotizacionDetalles;
	private List<OrdenCompra> ordenCompras;

	public Cotizacion() {
	}

	public Cotizacion(int idCotizacion) {
		this.idCotizacion = idCotizacion;
	}

	public Cotizacion(int idCotizacion, Solicitud solicitud, Integer aprobado, BigDecimal cargos, BigDecimal descuentos,
			Date fechaEnvio, Integer idMoneda, BigDecimal igv, BigDecimal neto, String observaciones,
			BigDecimal percepcion, BigDecimal subTotal, BigDecimal total, List<CotizacionDetalle> cotizacionDetalles,
			List<OrdenCompra> ordenCompras) {
		this.idCotizacion = idCotizacion;
		this.solicitud = solicitud;
		this.aprobado = aprobado;
		this.cargos = cargos;
		this.descuentos = descuentos;
		this.fechaEnvio = fechaEnvio;
		this.idMoneda = idMoneda;
		this.igv = igv;
		this.neto = neto;
		this.observaciones = observaciones;
		this.percepcion = percepcion;
		this.subTotal = subTotal;
		this.total = total;
		this.cotizacionDetalles = cotizacionDetalles;
		this.ordenCompras = ordenCompras;
	}

	@Id

	@Column(name = "idCotizacion", unique = true, nullable = false)
	public int getIdCotizacion() {
		return this.idCotizacion;
	}

	public void setIdCotizacion(int idCotizacion) {
		this.idCotizacion = idCotizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSolicitud")
	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	@Column(name = "aprobado")
	public Integer getAprobado() {
		return this.aprobado;
	}

	public void setAprobado(Integer aprobado) {
		this.aprobado = aprobado;
	}

	@Column(name = "cargos", precision = 12)
	public BigDecimal getCargos() {
		return this.cargos;
	}

	public void setCargos(BigDecimal cargos) {
		this.cargos = cargos;
	}

	@Column(name = "descuentos", precision = 12)
	public BigDecimal getDescuentos() {
		return this.descuentos;
	}

	public void setDescuentos(BigDecimal descuentos) {
		this.descuentos = descuentos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaEnvio", length = 10)
	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	@Column(name = "idMoneda")
	public Integer getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(Integer idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "igv", precision = 12)
	public BigDecimal getIgv() {
		return this.igv;
	}

	public void setIgv(BigDecimal igv) {
		this.igv = igv;
	}

	@Column(name = "neto", precision = 12)
	public BigDecimal getNeto() {
		return this.neto;
	}

	public void setNeto(BigDecimal neto) {
		this.neto = neto;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "percepcion", precision = 12)
	public BigDecimal getPercepcion() {
		return this.percepcion;
	}

	public void setPercepcion(BigDecimal percepcion) {
		this.percepcion = percepcion;
	}

	@Column(name = "subTotal", precision = 12)
	public BigDecimal getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(BigDecimal subTotal) {
		this.subTotal = subTotal;
	}

	@Column(name = "total", precision = 12)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cotizacion")
	public List<CotizacionDetalle> getCotizacionDetalles() {
		return this.cotizacionDetalles;
	}

	public void setCotizacionDetalles(List<CotizacionDetalle> cotizacionDetalles) {
		this.cotizacionDetalles = cotizacionDetalles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cotizacion")
	public List<OrdenCompra> getOrdenCompras() {
		return this.ordenCompras;
	}

	public void setOrdenCompras(List<OrdenCompra> ordenCompras) {
		this.ordenCompras = ordenCompras;
	}

}
