package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CotizaciondetalleId generated by hbm2java
 */
@Embeddable
public class CotizaciondetalleId implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column(name="IDCOTIZACIONDETALLE", nullable=false, precision=3)
     private int idcotizaciondetalle;

    @Column(name="IDCOTIZACION", nullable=false, precision=3)
     private int idcotizacion;

    public CotizaciondetalleId() {
    }

    public CotizaciondetalleId(int idcotizaciondetalle, int idcotizacion) {
       this.idcotizaciondetalle = idcotizaciondetalle;
       this.idcotizacion = idcotizacion;
    }

    public int getIdcotizaciondetalle() {
        return this.idcotizaciondetalle;
    }
    
    public void setIdcotizaciondetalle(int idcotizaciondetalle) {
        this.idcotizaciondetalle = idcotizaciondetalle;
    }

    public int getIdcotizacion() {
        return this.idcotizacion;
    }
    
    public void setIdcotizacion(int idcotizacion) {
        this.idcotizacion = idcotizacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CotizaciondetalleId) ) return false;
		 CotizaciondetalleId castOther = ( CotizaciondetalleId ) other; 
         
		 return (this.getIdcotizaciondetalle()==castOther.getIdcotizaciondetalle())
 && (this.getIdcotizacion()==castOther.getIdcotizacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdcotizaciondetalle();
         result = 37 * result + (int) this.getIdcotizacion();
         return result;
   }   


}


