package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DespachoxvehiculoId generated by hbm2java
 */
@Embeddable
public class DespachoxvehiculoId  implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
     private int iddespachoxvehiculo;
     private int iddespacho;

    public DespachoxvehiculoId() {
    }

    public DespachoxvehiculoId(int iddespachoxvehiculo, int iddespacho) {
       this.iddespachoxvehiculo = iddespachoxvehiculo;
       this.iddespacho = iddespacho;
    }
   


    @Column(name="IDDESPACHOXVEHICULO", nullable=false, precision=10, scale=0)
    public int getIddespachoxvehiculo() {
        return this.iddespachoxvehiculo;
    }
    
    public void setIddespachoxvehiculo(int iddespachoxvehiculo) {
        this.iddespachoxvehiculo = iddespachoxvehiculo;
    }


    @Column(name="IDDESPACHO", nullable=false, precision=10, scale=0)
    public int getIddespacho() {
        return this.iddespacho;
    }
    
    public void setIddespacho(int iddespacho) {
        this.iddespacho = iddespacho;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DespachoxvehiculoId) ) return false;
		 DespachoxvehiculoId castOther = ( DespachoxvehiculoId ) other; 
         
		 return (this.getIddespachoxvehiculo()==castOther.getIddespachoxvehiculo())
 && (this.getIddespacho()==castOther.getIddespacho());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIddespachoxvehiculo();
         result = 37 * result + (int) this.getIddespacho();
         return result;
   }   


}


