package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DespachoHist generated by hbm2java
 */
@Entity
@Table(name="despachoHist"
    ,schema="dbo"
    ,catalog="HORADADA"
)
public class DespachoHist  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idDespachoHist;
     private String descripcionMateria;
     private Integer diasStandby;
     private String direccionLlegada;
     private String direccionPartida;
     private Date fechaCarga;
     private Date fechaDescarga;
     private int idDespacho;
     private int idOrdenCompra;
     private int idTransportista;

    public DespachoHist() {
    }

	
    public DespachoHist(int idDespachoHist, int idDespacho, int idOrdenCompra, int idTransportista) {
        this.idDespachoHist = idDespachoHist;
        this.idDespacho = idDespacho;
        this.idOrdenCompra = idOrdenCompra;
        this.idTransportista = idTransportista;
    }
    public DespachoHist(int idDespachoHist, String descripcionMateria, Integer diasStandby, String direccionLlegada, String direccionPartida, Date fechaCarga, Date fechaDescarga, int idDespacho, int idOrdenCompra, int idTransportista) {
       this.idDespachoHist = idDespachoHist;
       this.descripcionMateria = descripcionMateria;
       this.diasStandby = diasStandby;
       this.direccionLlegada = direccionLlegada;
       this.direccionPartida = direccionPartida;
       this.fechaCarga = fechaCarga;
       this.fechaDescarga = fechaDescarga;
       this.idDespacho = idDespacho;
       this.idOrdenCompra = idOrdenCompra;
       this.idTransportista = idTransportista;
    }
   
     @Id 

    
    @Column(name="idDespachoHist", unique=true, nullable=false)
    public int getIdDespachoHist() {
        return this.idDespachoHist;
    }
    
    public void setIdDespachoHist(int idDespachoHist) {
        this.idDespachoHist = idDespachoHist;
    }

    
    @Column(name="descripcionMateria", length=50)
    public String getDescripcionMateria() {
        return this.descripcionMateria;
    }
    
    public void setDescripcionMateria(String descripcionMateria) {
        this.descripcionMateria = descripcionMateria;
    }

    
    @Column(name="diasStandby")
    public Integer getDiasStandby() {
        return this.diasStandby;
    }
    
    public void setDiasStandby(Integer diasStandby) {
        this.diasStandby = diasStandby;
    }

    
    @Column(name="direccionLlegada", length=65)
    public String getDireccionLlegada() {
        return this.direccionLlegada;
    }
    
    public void setDireccionLlegada(String direccionLlegada) {
        this.direccionLlegada = direccionLlegada;
    }

    
    @Column(name="direccionPartida", length=65)
    public String getDireccionPartida() {
        return this.direccionPartida;
    }
    
    public void setDireccionPartida(String direccionPartida) {
        this.direccionPartida = direccionPartida;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaCarga", length=10)
    public Date getFechaCarga() {
        return this.fechaCarga;
    }
    
    public void setFechaCarga(Date fechaCarga) {
        this.fechaCarga = fechaCarga;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaDescarga", length=10)
    public Date getFechaDescarga() {
        return this.fechaDescarga;
    }
    
    public void setFechaDescarga(Date fechaDescarga) {
        this.fechaDescarga = fechaDescarga;
    }

    
    @Column(name="idDespacho", nullable=false)
    public int getIdDespacho() {
        return this.idDespacho;
    }
    
    public void setIdDespacho(int idDespacho) {
        this.idDespacho = idDespacho;
    }

    
    @Column(name="idOrdenCompra", nullable=false)
    public int getIdOrdenCompra() {
        return this.idOrdenCompra;
    }
    
    public void setIdOrdenCompra(int idOrdenCompra) {
        this.idOrdenCompra = idOrdenCompra;
    }

    
    @Column(name="idTransportista", nullable=false)
    public int getIdTransportista() {
        return this.idTransportista;
    }
    
    public void setIdTransportista(int idTransportista) {
        this.idTransportista = idTransportista;
    }




}


