package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Despacho generated by hbm2java
 */
@Entity
@Table(name="DESPACHO"
    ,schema="HORADADA"
)
public class Despacho  implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
     private long iddespacho;
     private Cliente cliente;
     private Ordencompra ordencompra;
     private Long idestadodespacho;
     private String descripcionmateria;
     private String direccionpartida;
     private String direccionllegada;
     private Long diasestimados;
     private Date fechainicio;
     private Date fechafin;

    public Despacho() {
    }

	
    public Despacho(long iddespacho, Ordencompra ordencompra) {
        this.iddespacho = iddespacho;
        this.ordencompra = ordencompra;
    }
    public Despacho(long iddespacho, Cliente cliente, Ordencompra ordencompra, Long idestadodespacho, String descripcionmateria, String direccionpartida, String direccionllegada, Long diasestimados, Date fechainicio, Date fechafin) {
       this.iddespacho = iddespacho;
       this.cliente = cliente;
       this.ordencompra = ordencompra;
       this.idestadodespacho = idestadodespacho;
       this.descripcionmateria = descripcionmateria;
       this.direccionpartida = direccionpartida;
       this.direccionllegada = direccionllegada;
       this.diasestimados = diasestimados;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
    }
   
     @Id     
    @Column(name="IDDESPACHO", unique=true, nullable=false, precision=10, scale=0)
    public long getIddespacho() {
        return this.iddespacho;
    }
    
    public void setIddespacho(long iddespacho) {
        this.iddespacho = iddespacho;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCLIENTE")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDORDENCOMPRA", nullable=false)
    public Ordencompra getOrdencompra() {
        return this.ordencompra;
    }
    
    public void setOrdencompra(Ordencompra ordencompra) {
        this.ordencompra = ordencompra;
    }

    
    @Column(name="IDESTADODESPACHO", precision=10, scale=0)
    public Long getIdestadodespacho() {
        return this.idestadodespacho;
    }
    
    public void setIdestadodespacho(Long idestadodespacho) {
        this.idestadodespacho = idestadodespacho;
    }

    
    @Column(name="DESCRIPCIONMATERIA", length=50)
    public String getDescripcionmateria() {
        return this.descripcionmateria;
    }
    
    public void setDescripcionmateria(String descripcionmateria) {
        this.descripcionmateria = descripcionmateria;
    }

    
    @Column(name="DIRECCIONPARTIDA", length=45)
    public String getDireccionpartida() {
        return this.direccionpartida;
    }
    
    public void setDireccionpartida(String direccionpartida) {
        this.direccionpartida = direccionpartida;
    }

    
    @Column(name="DIRECCIONLLEGADA", length=45)
    public String getDireccionllegada() {
        return this.direccionllegada;
    }
    
    public void setDireccionllegada(String direccionllegada) {
        this.direccionllegada = direccionllegada;
    }

    
    @Column(name="DIASESTIMADOS", precision=10, scale=0)
    public Long getDiasestimados() {
        return this.diasestimados;
    }
    
    public void setDiasestimados(Long diasestimados) {
        this.diasestimados = diasestimados;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAINICIO", length=7)
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAFIN", length=7)
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }




}


