package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name="direccion"
    ,schema="dbo"
    ,catalog="HORADADA"
)
public class Direccion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idDireccion;
     private String calle;
     private String latitud;
     private String longitud;
     private String nombreDireccion;

    public Direccion() {
    }

	
    public Direccion(int idDireccion, String latitud, String longitud, String nombreDireccion) {
        this.idDireccion = idDireccion;
        this.latitud = latitud;
        this.longitud = longitud;
        this.nombreDireccion = nombreDireccion;
    }
    public Direccion(int idDireccion, String calle, String latitud, String longitud, String nombreDireccion) {
       this.idDireccion = idDireccion;
       this.calle = calle;
       this.latitud = latitud;
       this.longitud = longitud;
       this.nombreDireccion = nombreDireccion;
    }
   
     @Id 

 	@GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idDireccion", unique=true, nullable=false )
    public int getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(int idDireccion) {
        this.idDireccion = idDireccion;
    }

    
    @Column(name="calle", length=100)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="latitud", nullable=false, length=20)
    public String getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="longitud", nullable=false, length=20)
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="nombreDireccion", nullable=false, length=20)
    public String getNombreDireccion() {
        return this.nombreDireccion;
    }
    
    public void setNombreDireccion(String nombreDireccion) {
        this.nombreDireccion = nombreDireccion;
    }

}
