package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "factura", schema = "dbo", catalog = "HORADADA")
public class Factura implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private int idFactura;
	private Cliente cliente;
	private Integer correlativo;
	private BigDecimal costoStandby;
	private Date fechaEmision;
	private String guiaRemision;
	private Integer idDespacho;
	private Integer idMoneda;
	private Integer igv;
	private BigDecimal subTotal;
	private Integer total;
	private List<FacturaDetalle> facturaDetalles;
	private List<ValorizacionDetalle> valorizacionDetalles;

	public Factura() {
	}

	public Factura(int idFactura, Cliente cliente) {
		this.idFactura = idFactura;
		this.cliente = cliente;
	}

	public Factura(int idFactura, Cliente cliente, Integer correlativo, BigDecimal costoStandby, Date fechaEmision,
			String guiaRemision, Integer idDespacho, Integer idMoneda, Integer igv, BigDecimal subTotal, Integer total,
			List<FacturaDetalle> facturaDetalles, List<ValorizacionDetalle> valorizacionDetalles) {
		this.idFactura = idFactura;
		this.cliente = cliente;
		this.correlativo = correlativo;
		this.costoStandby = costoStandby;
		this.fechaEmision = fechaEmision;
		this.guiaRemision = guiaRemision;
		this.idDespacho = idDespacho;
		this.idMoneda = idMoneda;
		this.igv = igv;
		this.subTotal = subTotal;
		this.total = total;
		this.facturaDetalles = facturaDetalles;
		this.valorizacionDetalles = valorizacionDetalles;
	}

	@Id

	@Column(name = "idFactura", unique = true, nullable = false)
	public int getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(int idFactura) {
		this.idFactura = idFactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "correlativo")
	public Integer getCorrelativo() {
		return this.correlativo;
	}

	public void setCorrelativo(Integer correlativo) {
		this.correlativo = correlativo;
	}

	@Column(name = "costoStandby", precision = 12)
	public BigDecimal getCostoStandby() {
		return this.costoStandby;
	}

	public void setCostoStandby(BigDecimal costoStandby) {
		this.costoStandby = costoStandby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaEmision", length = 10)
	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	@Column(name = "guiaRemision", length = 20)
	public String getGuiaRemision() {
		return this.guiaRemision;
	}

	public void setGuiaRemision(String guiaRemision) {
		this.guiaRemision = guiaRemision;
	}

	@Column(name = "idDespacho")
	public Integer getIdDespacho() {
		return this.idDespacho;
	}

	public void setIdDespacho(Integer idDespacho) {
		this.idDespacho = idDespacho;
	}

	@Column(name = "idMoneda")
	public Integer getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(Integer idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "igv")
	public Integer getIgv() {
		return this.igv;
	}

	public void setIgv(Integer igv) {
		this.igv = igv;
	}

	@Column(name = "subTotal", precision = 12)
	public BigDecimal getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(BigDecimal subTotal) {
		this.subTotal = subTotal;
	}

	@Column(name = "total")
	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "factura")
	public List<FacturaDetalle> getFacturaDetalles() {
		return this.facturaDetalles;
	}

	public void setFacturaDetalles(List<FacturaDetalle> facturaDetalles) {
		this.facturaDetalles = facturaDetalles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "factura")
	public List<ValorizacionDetalle> getValorizacionDetalles() {
		return this.valorizacionDetalles;
	}

	public void setValorizacionDetalles(List<ValorizacionDetalle> valorizacionDetalles) {
		this.valorizacionDetalles = valorizacionDetalles;
	}

}
