package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Facturadetalle generated by hbm2java
 */
@Entity
@Table(name = "FACTURADETALLE", schema = "HORADADA")
public class Facturadetalle  {

	/**
	 * 
	 */
	

	@EmbeddedId
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "factura_detalle_seq")
	@SequenceGenerator(name = "factura_detalle_seq", sequenceName = "factura_detalle_sequence", allocationSize = 1)
	@AttributeOverrides({
			@AttributeOverride(name = "iddetallefactura", column = @Column(name = "IDDETALLEFACTURA", nullable = false, precision = 3)),
			@AttributeOverride(name = "idfactura", column = @Column(name = "IDFACTURA", nullable = false, precision = 3)) })
	private FacturadetalleId id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDFACTURA", nullable = false, insertable = false, updatable = false)
	private Factura factura;

	@Column(name = "CANTIDAD", precision = 3)
	private int cantidad;

	@Column(name = "DESCRIPCION", length = 160)
	private String descripcion;

	@Column(name = "PRECIOUNITARIO", precision = 12, scale = 2)
	private BigDecimal preciounitario;

	@Column(name = "VALORVENTA", precision = 12, scale = 2)
	private BigDecimal valorventa;

	public Facturadetalle() {
	}

	public Facturadetalle(FacturadetalleId id, Factura factura) {
		this.id = id;
		this.factura = factura;
	}

	public Facturadetalle(FacturadetalleId id, Factura factura, int cantidad, String descripcion,
			BigDecimal preciounitario, BigDecimal valorventa) {
		this.id = id;
		this.factura = factura;
		this.cantidad = cantidad;
		this.descripcion = descripcion;
		this.preciounitario = preciounitario;
		this.valorventa = valorventa;
	}

	public FacturadetalleId getId() {
		return this.id;
	}

	public void setId(FacturadetalleId id) {
		this.id = id;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getPreciounitario() {
		return this.preciounitario;
	}

	public void setPreciounitario(BigDecimal preciounitario) {
		this.preciounitario = preciounitario;
	}

	public BigDecimal getValorventa() {
		return this.valorventa;
	}

	public void setValorventa(BigDecimal valorventa) {
		this.valorventa = valorventa;
	}

}
