package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name="FACTURA"
    ,schema="HORADADA"
)
public class Factura  implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
     private long idfactura;
     private Cliente cliente;
     private Long iddespacho;
     private Long correlativo;
     private Date fechaemision;
     private String guiaremision;
     private BigDecimal costostandby;
     private BigDecimal subtotal;
     private Long igv;
     private Long total;
     private Long idmoneda;
     private Set<Facturadetalle> facturadetalles = new HashSet<Facturadetalle>(0);
     private Set<Valorizaciondetalle> valorizaciondetalles = new HashSet<Valorizaciondetalle>(0);

    public Factura() {
    }

	
    public Factura(long idfactura, Cliente cliente) {
        this.idfactura = idfactura;
        this.cliente = cliente;
    }
    public Factura(long idfactura, Cliente cliente, Long iddespacho, Long correlativo, Date fechaemision, String guiaremision, BigDecimal costostandby, BigDecimal subtotal, Long igv, Long total, Long idmoneda, Set<Facturadetalle> facturadetalles, Set<Valorizaciondetalle> valorizaciondetalles) {
       this.idfactura = idfactura;
       this.cliente = cliente;
       this.iddespacho = iddespacho;
       this.correlativo = correlativo;
       this.fechaemision = fechaemision;
       this.guiaremision = guiaremision;
       this.costostandby = costostandby;
       this.subtotal = subtotal;
       this.igv = igv;
       this.total = total;
       this.idmoneda = idmoneda;
       this.facturadetalles = facturadetalles;
       this.valorizaciondetalles = valorizaciondetalles;
    }
   
     @Id 

     @GeneratedValue(strategy=GenerationType.SEQUENCE)
    @Column(name="IDFACTURA", unique=true, nullable=false, precision=10, scale=0)
    public long getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(long idfactura) {
        this.idfactura = idfactura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCLIENTE", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="IDDESPACHO", precision=10, scale=0)
    public Long getIddespacho() {
        return this.iddespacho;
    }
    
    public void setIddespacho(Long iddespacho) {
        this.iddespacho = iddespacho;
    }

    
    @Column(name="CORRELATIVO", precision=10, scale=0)
    public Long getCorrelativo() {
        return this.correlativo;
    }
    
    public void setCorrelativo(Long correlativo) {
        this.correlativo = correlativo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAEMISION", length=7)
    public Date getFechaemision() {
        return this.fechaemision;
    }
    
    public void setFechaemision(Date fechaemision) {
        this.fechaemision = fechaemision;
    }

    
    @Column(name="GUIAREMISION", length=20)
    public String getGuiaremision() {
        return this.guiaremision;
    }
    
    public void setGuiaremision(String guiaremision) {
        this.guiaremision = guiaremision;
    }

    
    @Column(name="COSTOSTANDBY", precision=18)
    public BigDecimal getCostostandby() {
        return this.costostandby;
    }
    
    public void setCostostandby(BigDecimal costostandby) {
        this.costostandby = costostandby;
    }

    
    @Column(name="SUBTOTAL", precision=12)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="IGV", precision=12, scale=0)
    public Long getIgv() {
        return this.igv;
    }
    
    public void setIgv(Long igv) {
        this.igv = igv;
    }

    
    @Column(name="TOTAL", precision=12, scale=0)
    public Long getTotal() {
        return this.total;
    }
    
    public void setTotal(Long total) {
        this.total = total;
    }

    
    @Column(name="IDMONEDA", precision=10, scale=0)
    public Long getIdmoneda() {
        return this.idmoneda;
    }
    
    public void setIdmoneda(Long idmoneda) {
        this.idmoneda = idmoneda;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="factura")
    public Set<Facturadetalle> getFacturadetalles() {
        return this.facturadetalles;
    }
    
    public void setFacturadetalles(Set<Facturadetalle> facturadetalles) {
        this.facturadetalles = facturadetalles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="factura")
    public Set<Valorizaciondetalle> getValorizaciondetalles() {
        return this.valorizaciondetalles;
    }
    
    public void setValorizaciondetalles(Set<Valorizaciondetalle> valorizaciondetalles) {
        this.valorizaciondetalles = valorizaciondetalles;
    }




}


