package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FacturadetalleId generated by hbm2java
 */
@Embeddable
public class FacturadetalleId  implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
     private long iddetallefactura;
     private long idfactura;

    public FacturadetalleId() {
    }

    public FacturadetalleId(long iddetallefactura, long idfactura) {
       this.iddetallefactura = iddetallefactura;
       this.idfactura = idfactura;
    }
   


    @Column(name="IDDETALLEFACTURA", nullable=false, precision=10, scale=0)
    public long getIddetallefactura() {
        return this.iddetallefactura;
    }
    
    public void setIddetallefactura(long iddetallefactura) {
        this.iddetallefactura = iddetallefactura;
    }


    @Column(name="IDFACTURA", nullable=false, precision=10, scale=0)
    public long getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(long idfactura) {
        this.idfactura = idfactura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturadetalleId) ) return false;
		 FacturadetalleId castOther = ( FacturadetalleId ) other; 
         
		 return (this.getIddetallefactura()==castOther.getIddetallefactura())
 && (this.getIdfactura()==castOther.getIdfactura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIddetallefactura();
         result = 37 * result + (int) this.getIdfactura();
         return result;
   }   


}


