package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Facturadetalle generated by hbm2java
 */
@Entity
@Table(name="FACTURADETALLE"
    ,schema="HORADADA"
)
public class Facturadetalle  implements java.io.Serializable {


     private FacturadetalleId id;
     private Factura factura;
     private Long cantidad;
     private String descripcion;
     private BigDecimal preciounitario;
     private BigDecimal valorventa;

    public Facturadetalle() {
    }

	
    public Facturadetalle(FacturadetalleId id, Factura factura) {
        this.id = id;
        this.factura = factura;
    }
    public Facturadetalle(FacturadetalleId id, Factura factura, Long cantidad, String descripcion, BigDecimal preciounitario, BigDecimal valorventa) {
       this.id = id;
       this.factura = factura;
       this.cantidad = cantidad;
       this.descripcion = descripcion;
       this.preciounitario = preciounitario;
       this.valorventa = valorventa;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iddetallefactura", column=@Column(name="IDDETALLEFACTURA", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="idfactura", column=@Column(name="IDFACTURA", nullable=false, precision=10, scale=0) ) } )
    public FacturadetalleId getId() {
        return this.id;
    }
    
    public void setId(FacturadetalleId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDFACTURA", nullable=false, insertable=false, updatable=false)
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

    
    @Column(name="CANTIDAD", precision=10, scale=0)
    public Long getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Long cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="PRECIOUNITARIO", precision=12)
    public BigDecimal getPreciounitario() {
        return this.preciounitario;
    }
    
    public void setPreciounitario(BigDecimal preciounitario) {
        this.preciounitario = preciounitario;
    }

    
    @Column(name="VALORVENTA", precision=12)
    public BigDecimal getValorventa() {
        return this.valorventa;
    }
    
    public void setValorventa(BigDecimal valorventa) {
        this.valorventa = valorventa;
    }




}


