package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HistoricoPrecios generated by hbm2java
 */
@Entity
@Table(name="historicoPrecios"
    ,schema="dbo"
    ,catalog="HORADADA"
)
public class HistoricoPrecios  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idHistoricoPrecios;
     private String destino;
     private Integer longitudMetros;
     private String origen;
     private Integer medida;
     private BigDecimal precioIgv;
     private BigDecimal precioSubTotal;
     private BigDecimal precioPotal;
     private Integer idUnidadMedida;

    public HistoricoPrecios() {
    }

	
    public HistoricoPrecios(int idHistoricoPrecios) {
        this.idHistoricoPrecios = idHistoricoPrecios;
    }
    public HistoricoPrecios(int idHistoricoPrecios, String destino, Integer longitudMetros, String origen, Integer medida, BigDecimal precioIgv, BigDecimal precioSubTotal, BigDecimal precioPotal, Integer idUnidadMedida) {
       this.idHistoricoPrecios = idHistoricoPrecios;
       this.destino = destino;
       this.longitudMetros = longitudMetros;
       this.origen = origen;
       this.medida = medida;
       this.precioIgv = precioIgv;
       this.precioSubTotal = precioSubTotal;
       this.precioPotal = precioPotal;
       this.idUnidadMedida = idUnidadMedida;
    }
   
     @Id 

    
    @Column(name="idHistoricoPrecios", unique=true, nullable=false)
    public int getIdHistoricoPrecios() {
        return this.idHistoricoPrecios;
    }
    
    public void setIdHistoricoPrecios(int idHistoricoPrecios) {
        this.idHistoricoPrecios = idHistoricoPrecios;
    }

    
    @Column(name="destino", length=50)
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }

    
    @Column(name="longitudMetros")
    public Integer getLongitudMetros() {
        return this.longitudMetros;
    }
    
    public void setLongitudMetros(Integer longitudMetros) {
        this.longitudMetros = longitudMetros;
    }

    
    @Column(name="origen", length=50)
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    
    @Column(name="medida")
    public Integer getMedida() {
        return this.medida;
    }
    
    public void setMedida(Integer medida) {
        this.medida = medida;
    }

    
    @Column(name="precioIgv", precision=12)
    public BigDecimal getPrecioIgv() {
        return this.precioIgv;
    }
    
    public void setPrecioIgv(BigDecimal precioIgv) {
        this.precioIgv = precioIgv;
    }

    
    @Column(name="precioSubTotal", precision=12)
    public BigDecimal getPrecioSubTotal() {
        return this.precioSubTotal;
    }
    
    public void setPrecioSubTotal(BigDecimal precioSubTotal) {
        this.precioSubTotal = precioSubTotal;
    }

    
    @Column(name="precioPotal", precision=12)
    public BigDecimal getPrecioPotal() {
        return this.precioPotal;
    }
    
    public void setPrecioPotal(BigDecimal precioPotal) {
        this.precioPotal = precioPotal;
    }

    
    @Column(name="idUnidadMedida")
    public Integer getIdUnidadMedida() {
        return this.idUnidadMedida;
    }
    
    public void setIdUnidadMedida(Integer idUnidadMedida) {
        this.idUnidadMedida = idUnidadMedida;
    }




}


