package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Historicoprecios generated by hbm2java
 */
@Entity
@Table(name="HISTORICOPRECIOS"
    ,schema="HORADADA"
)
public class Historicoprecios  implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
     private long idhistoricoprecios;
     private String origen;
     private String destino;
     private Long pesotoneladas;
     private Long longitudmetros;
     private BigDecimal preciosubtotal;
     private BigDecimal precioigv;
     private BigDecimal preciototal;

    public Historicoprecios() {
    }

	
    public Historicoprecios(long idhistoricoprecios) {
        this.idhistoricoprecios = idhistoricoprecios;
    }
    public Historicoprecios(long idhistoricoprecios, String origen, String destino, Long pesotoneladas, Long longitudmetros, BigDecimal preciosubtotal, BigDecimal precioigv, BigDecimal preciototal) {
       this.idhistoricoprecios = idhistoricoprecios;
       this.origen = origen;
       this.destino = destino;
       this.pesotoneladas = pesotoneladas;
       this.longitudmetros = longitudmetros;
       this.preciosubtotal = preciosubtotal;
       this.precioigv = precioigv;
       this.preciototal = preciototal;
    }
   
     @Id 

     @GeneratedValue(strategy=GenerationType.SEQUENCE)
    @Column(name="IDHISTORICOPRECIOS", unique=true, nullable=false, precision=10, scale=0)
    public long getIdhistoricoprecios() {
        return this.idhistoricoprecios;
    }
    
    public void setIdhistoricoprecios(long idhistoricoprecios) {
        this.idhistoricoprecios = idhistoricoprecios;
    }

    
    @Column(name="ORIGEN", length=50)
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    
    @Column(name="DESTINO", length=50)
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }

    
    @Column(name="PESOTONELADAS", precision=10, scale=0)
    public Long getPesotoneladas() {
        return this.pesotoneladas;
    }
    
    public void setPesotoneladas(Long pesotoneladas) {
        this.pesotoneladas = pesotoneladas;
    }

    
    @Column(name="LONGITUDMETROS", precision=10, scale=0)
    public Long getLongitudmetros() {
        return this.longitudmetros;
    }
    
    public void setLongitudmetros(Long longitudmetros) {
        this.longitudmetros = longitudmetros;
    }

    
    @Column(name="PRECIOSUBTOTAL", precision=12)
    public BigDecimal getPreciosubtotal() {
        return this.preciosubtotal;
    }
    
    public void setPreciosubtotal(BigDecimal preciosubtotal) {
        this.preciosubtotal = preciosubtotal;
    }

    
    @Column(name="PRECIOIGV", precision=12)
    public BigDecimal getPrecioigv() {
        return this.precioigv;
    }
    
    public void setPrecioigv(BigDecimal precioigv) {
        this.precioigv = precioigv;
    }

    
    @Column(name="PRECIOTOTAL", precision=12)
    public BigDecimal getPreciototal() {
        return this.preciototal;
    }
    
    public void setPreciototal(BigDecimal preciototal) {
        this.preciototal = preciototal;
    }




}


