package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Observaciones generated by hbm2java
 */
@Entity
@Table(name = "OBSERVACIONES", schema = "HORADADA")
public class Observaciones  {

	/**
	 * 
	 */
	

	@Id
	@Column(name = "IDOBSERVACIONES", unique = true, nullable = false, precision = 3)
	private int idobservaciones;

	@Column(name = "IDDESPACHO", nullable = false, precision = 3)
	private int iddespacho;

	@Column(name = "OBSERVACIONDETALLE", length = 200)
	private String observaciondetalle;

	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHAINGRESO")
	private Date fechaingreso;

	public Observaciones() {
	}

	public Observaciones(int idobservaciones, int iddespacho) {
		this.idobservaciones = idobservaciones;
		this.iddespacho = iddespacho;
	}

	public Observaciones(int idobservaciones, int iddespacho, String observaciondetalle, Date fechaingreso) {
		this.idobservaciones = idobservaciones;
		this.iddespacho = iddespacho;
		this.observaciondetalle = observaciondetalle;
		this.fechaingreso = fechaingreso;
	}

	public int getIdobservaciones() {
		return this.idobservaciones;
	}

	public void setIdobservaciones(int idobservaciones) {
		this.idobservaciones = idobservaciones;
	}

	public int getIddespacho() {
		return this.iddespacho;
	}

	public void setIddespacho(int iddespacho) {
		this.iddespacho = iddespacho;
	}

	public String getObservaciondetalle() {
		return this.observaciondetalle;
	}

	public void setObservaciondetalle(String observaciondetalle) {
		this.observaciondetalle = observaciondetalle;
	}

	public Date getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}
}
