package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Observaciones generated by hbm2java
 */
@Entity
@Table(name="OBSERVACIONES"
    ,schema="HORADADA"
)
public class Observaciones  implements java.io.Serializable {


     private long idobservaciones;
     private long iddespacho;
     private String observaciondetalle;
     private Date fechaingreso;

    public Observaciones() {
    }

	
    public Observaciones(long idobservaciones, long iddespacho) {
        this.idobservaciones = idobservaciones;
        this.iddespacho = iddespacho;
    }
    public Observaciones(long idobservaciones, long iddespacho, String observaciondetalle, Date fechaingreso) {
       this.idobservaciones = idobservaciones;
       this.iddespacho = iddespacho;
       this.observaciondetalle = observaciondetalle;
       this.fechaingreso = fechaingreso;
    }
   
     @Id    
    @Column(name="IDOBSERVACIONES", unique=true, nullable=false, precision=10, scale=0)
    public long getIdobservaciones() {
        return this.idobservaciones;
    }
    
    public void setIdobservaciones(long idobservaciones) {
        this.idobservaciones = idobservaciones;
    }

    
    @Column(name="IDDESPACHO", nullable=false, precision=10, scale=0)
    public long getIddespacho() {
        return this.iddespacho;
    }
    
    public void setIddespacho(long iddespacho) {
        this.iddespacho = iddespacho;
    }

    
    @Column(name="OBSERVACIONDETALLE", length=200)
    public String getObservaciondetalle() {
        return this.observaciondetalle;
    }
    
    public void setObservaciondetalle(String observaciondetalle) {
        this.observaciondetalle = observaciondetalle;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAINGRESO", length=7)
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }
}


