package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdenCompra generated by hbm2java
 */
@Entity
@Table(name = "ordenCompra", schema = "dbo", catalog = "HORADADA")
public class OrdenCompra implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private int idOrdenCompra;
	private Cotizacion cotizacion;
	private Integer cargos;
	private BigDecimal descuentos;
	private Integer estadoOrdenCompra;
	private Date fechaEnvio;
	private Integer idMoneda;
	private BigDecimal igv;
	private BigDecimal neto;
	private String observaciones;
	private BigDecimal percepcion;
	private BigDecimal subTotal;
	private BigDecimal total;
	private List<Despacho> despachos;

	public OrdenCompra() {
	}

	public OrdenCompra(int idOrdenCompra) {
		this.idOrdenCompra = idOrdenCompra;
	}

	public OrdenCompra(int idOrdenCompra, Cotizacion cotizacion, Integer cargos, BigDecimal descuentos,
			Integer estadoOrdenCompra, Date fechaEnvio, Integer idMoneda, BigDecimal igv, BigDecimal neto,
			String observaciones, BigDecimal percepcion, BigDecimal subTotal, BigDecimal total, List<Despacho> despachos) {
		this.idOrdenCompra = idOrdenCompra;
		this.cotizacion = cotizacion;
		this.cargos = cargos;
		this.descuentos = descuentos;
		this.estadoOrdenCompra = estadoOrdenCompra;
		this.fechaEnvio = fechaEnvio;
		this.idMoneda = idMoneda;
		this.igv = igv;
		this.neto = neto;
		this.observaciones = observaciones;
		this.percepcion = percepcion;
		this.subTotal = subTotal;
		this.total = total;
		this.despachos = despachos;
	}

	@Id

	@Column(name = "idOrdenCompra", unique = true, nullable = false)
	public int getIdOrdenCompra() {
		return this.idOrdenCompra;
	}

	public void setIdOrdenCompra(int idOrdenCompra) {
		this.idOrdenCompra = idOrdenCompra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCotizacion")
	public Cotizacion getCotizacion() {
		return this.cotizacion;
	}

	public void setCotizacion(Cotizacion cotizacion) {
		this.cotizacion = cotizacion;
	}

	@Column(name = "cargos", precision = 9, scale = 0)
	public Integer getCargos() {
		return this.cargos;
	}

	public void setCargos(Integer cargos) {
		this.cargos = cargos;
	}

	@Column(name = "descuentos", precision = 12)
	public BigDecimal getDescuentos() {
		return this.descuentos;
	}

	public void setDescuentos(BigDecimal descuentos) {
		this.descuentos = descuentos;
	}

	@Column(name = "estadoOrdenCompra")
	public Integer getEstadoOrdenCompra() {
		return this.estadoOrdenCompra;
	}

	public void setEstadoOrdenCompra(Integer estadoOrdenCompra) {
		this.estadoOrdenCompra = estadoOrdenCompra;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaEnvio", length = 10)
	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	@Column(name = "idMoneda")
	public Integer getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(Integer idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "igv", precision = 12)
	public BigDecimal getIgv() {
		return this.igv;
	}

	public void setIgv(BigDecimal igv) {
		this.igv = igv;
	}

	@Column(name = "neto", precision = 12)
	public BigDecimal getNeto() {
		return this.neto;
	}

	public void setNeto(BigDecimal neto) {
		this.neto = neto;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "percepcion", precision = 12)
	public BigDecimal getPercepcion() {
		return this.percepcion;
	}

	public void setPercepcion(BigDecimal percepcion) {
		this.percepcion = percepcion;
	}

	@Column(name = "subTotal", precision = 12)
	public BigDecimal getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(BigDecimal subTotal) {
		this.subTotal = subTotal;
	}

	@Column(name = "total", precision = 12)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ordenCompra")
	public List<Despacho> getDespachos() {
		return this.despachos;
	}

	public void setDespachos(List<Despacho> despachos) {
		this.despachos = despachos;
	}

}
