package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ordencompra generated by hbm2java
 */
@Entity
@Table(name="ORDENCOMPRA"
    ,schema="HORADADA"
)
public class Ordencompra  implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
     private long idordencompra;
     private Cotizacion cotizacion;
     private Date fechaenvio;
     private BigDecimal subtotal;
     private BigDecimal descuentos;
     private BigDecimal cargos;
     private BigDecimal neto;
     private BigDecimal igv;
     private BigDecimal percepcion;
     private BigDecimal total;
     private String observaciones;
     private Long idmoneda;
     private Integer estadoordencompra;
     private Set<Ordencompradetalle> ordencompradetalles = new HashSet<Ordencompradetalle>(0);
     private Set<Despacho> despachos = new HashSet<Despacho>(0);

    public Ordencompra() {
    }

	
    public Ordencompra(long idordencompra) {
        this.idordencompra = idordencompra;
    }
    public Ordencompra(long idordencompra, Cotizacion cotizacion, Date fechaenvio, BigDecimal subtotal, BigDecimal descuentos, BigDecimal cargos, BigDecimal neto, BigDecimal igv, BigDecimal percepcion, BigDecimal total, String observaciones, Long idmoneda, Integer estadoordencompra, Set<Ordencompradetalle> ordencompradetalles, Set<Despacho> despachos) {
       this.idordencompra = idordencompra;
       this.cotizacion = cotizacion;
       this.fechaenvio = fechaenvio;
       this.subtotal = subtotal;
       this.descuentos = descuentos;
       this.cargos = cargos;
       this.neto = neto;
       this.igv = igv;
       this.percepcion = percepcion;
       this.total = total;
       this.observaciones = observaciones;
       this.idmoneda = idmoneda;
       this.estadoordencompra = estadoordencompra;
       this.ordencompradetalles = ordencompradetalles;
       this.despachos = despachos;
    }
   
     @Id 

    
    @Column(name="IDORDENCOMPRA", unique=true, nullable=false, precision=10, scale=0)
    public long getIdordencompra() {
        return this.idordencompra;
    }
    
    public void setIdordencompra(long idordencompra) {
        this.idordencompra = idordencompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCOTIZACION")
    public Cotizacion getCotizacion() {
        return this.cotizacion;
    }
    
    public void setCotizacion(Cotizacion cotizacion) {
        this.cotizacion = cotizacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAENVIO", length=7)
    public Date getFechaenvio() {
        return this.fechaenvio;
    }
    
    public void setFechaenvio(Date fechaenvio) {
        this.fechaenvio = fechaenvio;
    }

    
    @Column(name="SUBTOTAL", precision=9)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="DESCUENTOS", precision=9)
    public BigDecimal getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(BigDecimal descuentos) {
        this.descuentos = descuentos;
    }

    
    @Column(name="CARGOS", precision=9)
    public BigDecimal getCargos() {
        return this.cargos;
    }
    
    public void setCargos(BigDecimal cargos) {
        this.cargos = cargos;
    }

    
    @Column(name="NETO", precision=9)
    public BigDecimal getNeto() {
        return this.neto;
    }
    
    public void setNeto(BigDecimal neto) {
        this.neto = neto;
    }

    
    @Column(name="IGV", precision=9)
    public BigDecimal getIgv() {
        return this.igv;
    }
    
    public void setIgv(BigDecimal igv) {
        this.igv = igv;
    }

    
    @Column(name="PERCEPCION", precision=9)
    public BigDecimal getPercepcion() {
        return this.percepcion;
    }
    
    public void setPercepcion(BigDecimal percepcion) {
        this.percepcion = percepcion;
    }

    
    @Column(name="TOTAL", precision=9)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    
    @Column(name="OBSERVACIONES", length=250)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="IDMONEDA", precision=10, scale=0)
    public Long getIdmoneda() {
        return this.idmoneda;
    }
    
    public void setIdmoneda(Long idmoneda) {
        this.idmoneda = idmoneda;
    }

    
    @Column(name="ESTADOORDENCOMPRA", precision=5, scale=0)
    public Integer getEstadoordencompra() {
        return this.estadoordencompra;
    }
    
    public void setEstadoordencompra(Integer estadoordencompra) {
        this.estadoordencompra = estadoordencompra;
    }
    
@OneToMany(fetch=FetchType.LAZY, mappedBy="ordencompra")
    public Set<Ordencompradetalle> getOrdencompradetalles() {
        return this.ordencompradetalles;
    }
    
    public void setOrdencompradetalles(Set<Ordencompradetalle> ordencompradetalles) {
        this.ordencompradetalles = ordencompradetalles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordencompra")
    public Set<Despacho> getDespachos() {
        return this.despachos;
    }
    
    public void setDespachos(Set<Despacho> despachos) {
        this.despachos = despachos;
    }
}


