package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedStoredProcedureQuery;
import javax.persistence.OneToMany;
import javax.persistence.ParameterMode;
import javax.persistence.SequenceGenerator;
import javax.persistence.StoredProcedureParameter;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "PERSONA", schema = "HORADADA")
@NamedStoredProcedureQuery(name = "persona.cambiaPersona", 
		                  procedureName = "mant_persona1",
		                  parameters = {
		                     @StoredProcedureParameter(mode = ParameterMode.IN, name = "v_tipopersona", type = Integer.class),
		                     @StoredProcedureParameter(mode = ParameterMode.IN, name = "v_idpersona", type = Integer.class)
		                  })
public class Persona  {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "persona_seq")
	@SequenceGenerator(name = "persona_seq", sequenceName = "persona_sequence", allocationSize = 1)
	@Column(name = "IDPERSONA", unique = true, nullable = false, precision = 3)
	private int idpersona;

	@Column(name = "PRIMERNOMBRE", length = 25)
	private String primernombre;

	@Column(name = "SEGUNDONOMBRE", length = 25)
	private String segundonombre;

	@Column(name = "PRIMERAPELLIDO", length = 25)
	private String primerapellido;

	@Column(name = "SEGUNDOAPELLIDO", length = 25)
	private String segundoapellido;

	@Column(name = "TIPOPERSONA", nullable = false, precision = 3)
	private int tipopersona;

	@Column(name = "CODTIPODOCUMENTO", precision = 3)
	private int codtipodocumento;

	@Column(name = "NUMERODOCUMENTO", precision = 3)
	private int numerodocumento;

	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHANACIMIENTO")
	private Date fechanacimiento;

	@Column(name = "EDAD", length = 2)
	private String edad;

	@Column(name = "DIRECCION", length = 60)
	private String direccion;

	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHACREACION")
	private Date fechacreacion;

	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHAUPDATE")
	private Date fechaupdate;

	@Column(name = "TELEFONO", length = 40)
	private String telefono;

	@Column(name = "CORREOELECTRONICO", length = 60)
	private String correoelectronico;

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "persona")
	private Set<Transportista> transportistas = new HashSet<Transportista>(0);

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "persona")
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "persona")
	private Set<Contacto> contacto = new HashSet<Contacto>(0);

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "persona")
	private Set<Telefono> telefonomonitoreos = new HashSet<Telefono>(0);

	public Persona() {
	}

	public Persona(int idpersona, int tipopersona) {
		this.idpersona = idpersona;
		this.tipopersona = tipopersona;
	}

	public Persona(int idpersona, String primernombre, String segundonombre, String primerapellido,
			String segundoapellido, int tipopersona, int codtipodocumento, int numerodocumento, Date fechanacimiento,
			String edad, String direccion, Date fechacreacion, Date fechaupdate, String telefono,
			String correoelectronico, Set<Transportista> transportistas, Set<Usuario> usuarios, Set<Contacto> contacto,
			Set<Telefono> telefonomonitoreos) {
		this.idpersona = idpersona;
		this.primernombre = primernombre;
		this.segundonombre = segundonombre;
		this.primerapellido = primerapellido;
		this.segundoapellido = segundoapellido;
		this.tipopersona = tipopersona;
		this.codtipodocumento = codtipodocumento;
		this.numerodocumento = numerodocumento;
		this.fechanacimiento = fechanacimiento;
		this.edad = edad;
		this.direccion = direccion;
		this.fechacreacion = fechacreacion;
		this.fechaupdate = fechaupdate;
		this.telefono = telefono;
		this.correoelectronico = correoelectronico;
		this.transportistas = transportistas;
		this.usuarios = usuarios;
		this.contacto = contacto;
		this.telefonomonitoreos = telefonomonitoreos;
	}

	public int getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(int idpersona) {
		this.idpersona = idpersona;
	}

	public String getPrimernombre() {
		return this.primernombre;
	}

	public void setPrimernombre(String primernombre) {
		this.primernombre = primernombre;
	}

	public String getSegundonombre() {
		return this.segundonombre;
	}

	public void setSegundonombre(String segundonombre) {
		this.segundonombre = segundonombre;
	}

	public String getPrimerapellido() {
		return this.primerapellido;
	}

	public void setPrimerapellido(String primerapellido) {
		this.primerapellido = primerapellido;
	}

	public String getSegundoapellido() {
		return this.segundoapellido;
	}

	public void setSegundoapellido(String segundoapellido) {
		this.segundoapellido = segundoapellido;
	}

	public int getTipopersona() {
		return this.tipopersona;
	}

	public void setTipopersona(int tipopersona) {
		this.tipopersona = tipopersona;
	}

	public int getCodtipodocumento() {
		return this.codtipodocumento;
	}

	public void setCodtipodocumento(int codtipodocumento) {
		this.codtipodocumento = codtipodocumento;
	}

	public int getNumerodocumento() {
		return this.numerodocumento;
	}

	public void setNumerodocumento(int numerodocumento) {
		this.numerodocumento = numerodocumento;
	}

	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public String getEdad() {
		return this.edad;
	}

	public void setEdad(String edad) {
		this.edad = edad;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	public Date getFechaupdate() {
		return this.fechaupdate;
	}

	public void setFechaupdate(Date fechaupdate) {
		this.fechaupdate = fechaupdate;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreoelectronico() {
		return this.correoelectronico;
	}

	public void setCorreoelectronico(String correoelectronico) {
		this.correoelectronico = correoelectronico;
	}

	public Set<Transportista> getTransportistas() {
		return this.transportistas;
	}

	public void setTransportistas(Set<Transportista> transportistas) {
		this.transportistas = transportistas;
	}

	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	public Set<Contacto> getContacto() {
		return this.contacto;
	}

	public void setContacto(Set<Contacto> contacto) {
		this.contacto = contacto;
	}

	public Set<Telefono> getTelefonomonitoreos() {
		return this.telefonomonitoreos;
	}

	public void setTelefonomonitoreos(Set<Telefono> telefonomonitoreos) {
		this.telefonomonitoreos = telefonomonitoreos;
	}
}