package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * RoleUsuario generated by hbm2java
 */
@Entity
@Table(name="roleUsuario"
    ,schema="dbo"
    ,catalog="HORADADA"
    , uniqueConstraints = @UniqueConstraint(columnNames={"nombreRol", "nombreUsuario"}) 
)
public class RoleUsuario  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idRoleUsuario;
     private Usuario usuario;
     private Date fechaCreacion;
     private String nombreRol;

    public RoleUsuario() {
    }

	
    public RoleUsuario(int idRoleUsuario, Usuario usuario) {
        this.idRoleUsuario = idRoleUsuario;
        this.usuario = usuario;
    }
    public RoleUsuario(int idRoleUsuario, Usuario usuario, Date fechaCreacion, String nombreRol) {
       this.idRoleUsuario = idRoleUsuario;
       this.usuario = usuario;
       this.fechaCreacion = fechaCreacion;
       this.nombreRol = nombreRol;
    }
   
     @Id 

    
    @Column(name="idRoleUsuario", unique=true, nullable=false)
    public int getIdRoleUsuario() {
        return this.idRoleUsuario;
    }
    
    public void setIdRoleUsuario(int idRoleUsuario) {
        this.idRoleUsuario = idRoleUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nombreUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaCreacion", length=10)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="nombreRol", length=25)
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }




}


