package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "solicitud", schema = "dbo", catalog = "HORADADA")
public class Solicitud implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private int idSolicitud;
	private Cliente cliente;
	private Integer estado;
	private Date fechaRecepcion;
	private String requerimiento;
	private List<Cotizacion> cotizacions;

	public Solicitud() {
	}

	public Solicitud(int idSolicitud, Cliente cliente) {
		this.idSolicitud = idSolicitud;
		this.cliente = cliente;
	}

	public Solicitud(int idSolicitud, Cliente cliente, Integer estado, Date fechaRecepcion, String requerimiento,
			List<Cotizacion> cotizacions) {
		this.idSolicitud = idSolicitud;
		this.cliente = cliente;
		this.estado = estado;
		this.fechaRecepcion = fechaRecepcion;
		this.requerimiento = requerimiento;
		this.cotizacions = cotizacions;
	}

	@Id

	@Column(name = "idSolicitud", unique = true, nullable = false)
	public int getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(int idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaRecepcion", length = 10)
	public Date getFechaRecepcion() {
		return this.fechaRecepcion;
	}

	public void setFechaRecepcion(Date fechaRecepcion) {
		this.fechaRecepcion = fechaRecepcion;
	}

	@Column(name = "requerimiento", length = 100)
	public String getRequerimiento() {
		return this.requerimiento;
	}

	public void setRequerimiento(String requerimiento) {
		this.requerimiento = requerimiento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitud")
	public List<Cotizacion> getCotizacions() {
		return this.cotizacions;
	}

	public void setCotizacions(List<Cotizacion> cotizacions) {
		this.cotizacions = cotizacions;
	}

}
