package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name="SOLICITUD"
    ,schema="HORADADA"
)
public class Solicitud  implements java.io.Serializable {


     private long idsolicitud;
     private Cliente cliente;
     private Date fecharecepcion;
     private String requerimiento;
     private Set cotizacions = new HashSet(0);

    public Solicitud() {
    }

	
    public Solicitud(long idsolicitud, Cliente cliente) {
        this.idsolicitud = idsolicitud;
        this.cliente = cliente;
    }
    public Solicitud(long idsolicitud, Cliente cliente, Date fecharecepcion, String requerimiento, Set cotizacions) {
       this.idsolicitud = idsolicitud;
       this.cliente = cliente;
       this.fecharecepcion = fecharecepcion;
       this.requerimiento = requerimiento;
       this.cotizacions = cotizacions;
    }
   
     @Id 

    
    @Column(name="IDSOLICITUD", unique=true, nullable=false, precision=10, scale=0)
    public long getIdsolicitud() {
        return this.idsolicitud;
    }
    
    public void setIdsolicitud(long idsolicitud) {
        this.idsolicitud = idsolicitud;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDCLIENTE", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHARECEPCION", length=7)
    public Date getFecharecepcion() {
        return this.fecharecepcion;
    }
    
    public void setFecharecepcion(Date fecharecepcion) {
        this.fecharecepcion = fecharecepcion;
    }

    
    @Column(name="REQUERIMIENTO", length=200)
    public String getRequerimiento() {
        return this.requerimiento;
    }
    
    public void setRequerimiento(String requerimiento) {
        this.requerimiento = requerimiento;
    }

    /*@OneToMany(fetch=FetchType.EAGER, mappedBy="solicitud")
    public Set getCotizacions() {
        return this.cotizacions;
    }
    
    public void setCotizacions(Set cotizacions) {
        this.cotizacions = cotizacions;
    }*/




}


