package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TablaMaestra generated by hbm2java
 */
@Entity
@Table(name="tablaMaestra"
    ,schema="dbo"
    ,catalog="HORADADA"
)
public class TablaMaestra  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idRegistro;
     private String clave1;
     private String clave2;
     private String clave3;
     private Date fechaCreacion;
     private String idTablaMaestra;
     private String valor1;
     private String valor2;
     private String valor3;

    public TablaMaestra() {
    }

	
    public TablaMaestra(int idRegistro, String idTablaMaestra) {
        this.idRegistro = idRegistro;
        this.idTablaMaestra = idTablaMaestra;
    }
    public TablaMaestra(int idRegistro, String clave1, String clave2, String clave3, Date fechaCreacion, String idTablaMaestra, String valor1, String valor2, String valor3) {
       this.idRegistro = idRegistro;
       this.clave1 = clave1;
       this.clave2 = clave2;
       this.clave3 = clave3;
       this.fechaCreacion = fechaCreacion;
       this.idTablaMaestra = idTablaMaestra;
       this.valor1 = valor1;
       this.valor2 = valor2;
       this.valor3 = valor3;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="idRegistro", unique=true, nullable=false)
    public int getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(int idRegistro) {
        this.idRegistro = idRegistro;
    }

    
    @Column(name="clave1", length=15)
    public String getClave1() {
        return this.clave1;
    }
    
    public void setClave1(String clave1) {
        this.clave1 = clave1;
    }

    
    @Column(name="clave2", length=15)
    public String getClave2() {
        return this.clave2;
    }
    
    public void setClave2(String clave2) {
        this.clave2 = clave2;
    }

    
    @Column(name="clave3", length=15)
    public String getClave3() {
        return this.clave3;
    }
    
    public void setClave3(String clave3) {
        this.clave3 = clave3;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaCreacion", length=10)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="idTablaMaestra", nullable=false, length=7)
    public String getIdTablaMaestra() {
        return this.idTablaMaestra;
    }
    
    public void setIdTablaMaestra(String idTablaMaestra) {
        this.idTablaMaestra = idTablaMaestra;
    }

    
    @Column(name="valor1", length=15)
    public String getValor1() {
        return this.valor1;
    }
    
    public void setValor1(String valor1) {
        this.valor1 = valor1;
    }

    
    @Column(name="valor2", length=15)
    public String getValor2() {
        return this.valor2;
    }
    
    public void setValor2(String valor2) {
        this.valor2 = valor2;
    }

    
    @Column(name="valor3", length=15)
    public String getValor3() {
        return this.valor3;
    }
    
    public void setValor3(String valor3) {
        this.valor3 = valor3;
    }




}


