package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tablamaestra generated by hbm2java
 */
@Entity
@Table(name="TABLAMAESTRA"
    ,schema="HORADADA"
)
public class Tablamaestra  implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
     private int idregistro;
     private String idtablamaestra;
     private String descripcion;
     private String clave1;
     private String clave2;
     private String clave3;
     private String valor1;
     private String valor2;
     private String valor3;
     private Date fechacreacion;



	public Tablamaestra() {
    }

	
    public Tablamaestra(int idregistro, String idtablamaestra) {
        this.idregistro = idregistro;
        this.idtablamaestra = idtablamaestra;
    }
    public Tablamaestra(int idregistro, String idtablamaestra, String descripcion, String clave1, String clave2, String clave3, String valor1, String valor2, String valor3,Date fechacreacion) {
       this.idregistro = idregistro;
       this.idtablamaestra = idtablamaestra;
       this.descripcion = descripcion;
       this.clave1 = clave1;
       this.clave2 = clave2;
       this.clave3 = clave3;
       this.valor1 = valor1;
       this.valor2 = valor2;
       this.valor3 = valor3;
       this.fechacreacion = fechacreacion;
    }
   
     @Id 

     @GeneratedValue(strategy=GenerationType.SEQUENCE , generator = "maestra_seq") @SequenceGenerator ( 
    		    name = "maestra_seq" , 
    		    sequenceName = "maestra_sequence" , 
    		    allocationSize = 1 )
    @Column(name="IDREGISTRO", unique=true, nullable=false, precision=10, scale=0)
    public int getIdregistro() {
        return this.idregistro;
    }
    
    public void setIdregistro(int idregistro) {
        this.idregistro = idregistro;
    }

    
    @Column(name="IDTABLAMAESTRA", nullable=false, length=7)
    public String getIdtablamaestra() {
        return this.idtablamaestra;
    }
    
    public void setIdtablamaestra(String idtablamaestra) {
        this.idtablamaestra = idtablamaestra;
    }

    
    @Column(name="DESCRIPCION", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CLAVE1", length=15)
    public String getClave1() {
        return this.clave1;
    }
    
    public void setClave1(String clave1) {
        this.clave1 = clave1;
    }

    
    @Column(name="CLAVE2", length=15)
    public String getClave2() {
        return this.clave2;
    }
    
    public void setClave2(String clave2) {
        this.clave2 = clave2;
    }

    
    @Column(name="CLAVE3", length=15)
    public String getClave3() {
        return this.clave3;
    }
    
    public void setClave3(String clave3) {
        this.clave3 = clave3;
    }

    
    @Column(name="VALOR1", length=15)
    public String getValor1() {
        return this.valor1;
    }
    
    public void setValor1(String valor1) {
        this.valor1 = valor1;
    }

    
    @Column(name="VALOR2", length=15)
    public String getValor2() {
        return this.valor2;
    }
    
    public void setValor2(String valor2) {
        this.valor2 = valor2;
    }

    
    @Column(name="VALOR3", length=15)
    public String getValor3() {
        return this.valor3;
    }
    
    public void setValor3(String valor3) {
        this.valor3 = valor3;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHACREACION", length=7)
   public Date getFechacreacion() {
		return fechacreacion;
	}


	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}



}


