package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TelefonoMonitoreo generated by hbm2java
 */
@Entity
@Table(name="telefonoMonitoreo"
    ,schema="dbo"
    ,catalog="HORADADA"
)
public class TelefonoMonitoreo  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTelefono;
     private Persona persona;
     private Integer idOperador;
     private Integer idTipoTelefono;
     private String imei;
     private String numeroTelefono;

    public TelefonoMonitoreo() {
    }

	
    public TelefonoMonitoreo(int idTelefono) {
        this.idTelefono = idTelefono;
    }
    public TelefonoMonitoreo(int idTelefono, Persona persona, Integer idOperador, Integer idTipoTelefono, String imei, String numeroTelefono) {
       this.idTelefono = idTelefono;
       this.persona = persona;
       this.idOperador = idOperador;
       this.idTipoTelefono = idTipoTelefono;
       this.imei = imei;
       this.numeroTelefono = numeroTelefono;
    }
   
     @Id 

    
    @Column(name="idTelefono", unique=true, nullable=false)
    public int getIdTelefono() {
        return this.idTelefono;
    }
    
    public void setIdTelefono(int idTelefono) {
        this.idTelefono = idTelefono;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPersona")
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="idOperador")
    public Integer getIdOperador() {
        return this.idOperador;
    }
    
    public void setIdOperador(Integer idOperador) {
        this.idOperador = idOperador;
    }

    
    @Column(name="idTipoTelefono")
    public Integer getIdTipoTelefono() {
        return this.idTipoTelefono;
    }
    
    public void setIdTipoTelefono(Integer idTipoTelefono) {
        this.idTipoTelefono = idTipoTelefono;
    }

    
    @Column(name="imei", length=20)
    public String getImei() {
        return this.imei;
    }
    
    public void setImei(String imei) {
        this.imei = imei;
    }

    
    @Column(name="numeroTelefono", length=18)
    public String getNumeroTelefono() {
        return this.numeroTelefono;
    }
    
    public void setNumeroTelefono(String numeroTelefono) {
        this.numeroTelefono = numeroTelefono;
    }




}


