package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TelefonomonitoreoId generated by hbm2java
 */
@Embeddable
public class TelefonomonitoreoId  implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
     private int idtelefono;
     private int idpersona;

    public TelefonomonitoreoId() {
    }

    public TelefonomonitoreoId(int idtelefono, int idpersona) {
       this.idtelefono = idtelefono;
       this.idpersona = idpersona;
    }
   


    @Column(name="IDTELEFONO", nullable=false, precision=10, scale=0)
    public int getIdtelefono() {
        return this.idtelefono;
    }
    
    public void setIdtelefono(int idtelefono) {
        this.idtelefono = idtelefono;
    }


    @Column(name="IDPERSONA", nullable=false, precision=10, scale=0)
    public int getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(int idpersona) {
        this.idpersona = idpersona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TelefonomonitoreoId) ) return false;
		 TelefonomonitoreoId castOther = ( TelefonomonitoreoId ) other; 
         
		 return (this.getIdtelefono()==castOther.getIdtelefono())
 && (this.getIdpersona()==castOther.getIdpersona());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdtelefono();
         result = 37 * result + (int) this.getIdpersona();
         return result;
   }   


}


