package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1



import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TelefonomonitoreoId generated by hbm2java
 */
@Embeddable
public class TelefonoId implements Serializable {

	private static final long serialVersionUID = 1L;

	@Column(name = "IDTELEFONO", nullable = false, precision = 10, scale = 0)
	private int idtelefono;

	@Column(name = "IDPERSONA", nullable = false, precision = 10, scale = 0)
	private int idpersona;

	public TelefonoId() {
	}

	public TelefonoId(int idtelefono, int idpersona) {
		this.idtelefono = idtelefono;
		this.idpersona = idpersona;
	}

	public int getIdtelefono() {
		return this.idtelefono;
	}

	public void setIdtelefono(int idtelefono) {
		this.idtelefono = idtelefono;
	}

	public int getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(int idpersona) {
		this.idpersona = idpersona;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TelefonoId))
			return false;
		TelefonoId castOther = (TelefonoId) other;

		return (this.getIdtelefono() == castOther.getIdtelefono()) && (this.getIdpersona() == castOther.getIdpersona());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdtelefono();
		result = 37 * result + (int) this.getIdpersona();
		return result;
	}

}
