package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Tiposervicio generated by hbm2java
 */
@Entity
@Table(name = "TIPOSERVICIO", schema = "HORADADA")
public class Tiposervicio  {

	/**
	 * 
	 */
	

	@Id
	@Column(name = "IDSERVICIO", unique = true, nullable = false, precision = 3)
	private int idservicio;

	@Column(name = "NOMBRESERVICIO", length = 50)
	private String nombreservicio;

	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHAINGRESO")
	private Date fechaingreso;

	public Tiposervicio() {
	}

	public Tiposervicio(int idservicio) {
		this.idservicio = idservicio;
	}

	public Tiposervicio(int idservicio, String nombreservicio, Date fechaingreso) {
		this.idservicio = idservicio;
		this.nombreservicio = nombreservicio;
		this.fechaingreso = fechaingreso;
	}

	public int getIdservicio() {
		return this.idservicio;
	}

	public void setIdservicio(int idservicio) {
		this.idservicio = idservicio;
	}

	public String getNombreservicio() {
		return this.nombreservicio;
	}

	public void setNombreservicio(String nombreservicio) {
		this.nombreservicio = nombreservicio;
	}

	public Date getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

}
