package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Tiposervicio generated by hbm2java
 */
@Entity
@Table(name="TIPOSERVICIO"
    ,schema="HORADADA"
)
public class Tiposervicio  implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
     private int idservicio;
     private String nombreservicio;
     private Date fechaingreso;

    public Tiposervicio() {
    }

	
    public Tiposervicio(int idservicio) {
        this.idservicio = idservicio;
    }
    public Tiposervicio(int idservicio, String nombreservicio, Date fechaingreso) {
       this.idservicio = idservicio;
       this.nombreservicio = nombreservicio;
       this.fechaingreso = fechaingreso;
    }
   
     @Id 

    
    @Column(name="IDSERVICIO", unique=true, nullable=false, precision=10, scale=0)
    public int getIdservicio() {
        return this.idservicio;
    }
    
    public void setIdservicio(int idservicio) {
        this.idservicio = idservicio;
    }

    
    @Column(name="NOMBRESERVICIO", length=50)
    public String getNombreservicio() {
        return this.nombreservicio;
    }
    
    public void setNombreservicio(String nombreservicio) {
        this.nombreservicio = nombreservicio;
    }

    @DateTimeFormat(pattern = "dd/MM/yyyy")
    @Temporal(TemporalType.DATE)
    @Column(name="FECHAINGRESO", length=7)
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }




}


