package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tiposervicio generated by hbm2java
 */
@Entity
@Table(name="TIPOSERVICIO")
public class Tiposervicio {


     private long idservicio;
     private String nombreservicio;
     private Date fechaingreso;

    public Tiposervicio() {
    }

	
    public Tiposervicio(long idservicio) {
        this.idservicio = idservicio;
    }
    public Tiposervicio(long idservicio, String nombreservicio, Date fechaingreso) {
       this.idservicio = idservicio;
       this.nombreservicio = nombreservicio;
       this.fechaingreso = fechaingreso;
    }
   
     @Id 

    
    @Column(name="IDSERVICIO", unique=true, nullable=false, precision=10, scale=0)
    public long getIdservicio() {
        return this.idservicio;
    }
    
    public void setIdservicio(long idservicio) {
        this.idservicio = idservicio;
    }

    
    @Column(name="NOMBRESERVICIO", length=50)
    public String getNombreservicio() {
        return this.nombreservicio;
    }
    
    public void setNombreservicio(String nombreservicio) {
        this.nombreservicio = nombreservicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAINGRESO", length=7)
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }




}


