package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Transportista generated by hbm2java
 */
@Entity
@Table(name = "transportista", schema = "dbo", catalog = "HORADADA", uniqueConstraints = @UniqueConstraint(columnNames = "idPersona"))
public class Transportista implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private int idTransportista;
	private Persona persona;
	private String catLicencia;
	private Integer idSituacionTransportista;
	private String nroLicencia;
	private List<Vehiculo> vehiculos;

	public Transportista() {
	}

	public Transportista(int idTransportista, Persona persona, String nroLicencia) {
		this.idTransportista = idTransportista;
		this.persona = persona;
		this.nroLicencia = nroLicencia;
	}

	public Transportista(int idTransportista, Persona persona, String catLicencia, Integer idSituacionTransportista,
			String nroLicencia, List<Vehiculo> vehiculos) {
		this.idTransportista = idTransportista;
		this.persona = persona;
		this.catLicencia = catLicencia;
		this.idSituacionTransportista = idSituacionTransportista;
		this.nroLicencia = nroLicencia;
		this.vehiculos = vehiculos;
	}

	@Id

	@Column(name = "idTransportista", unique = true, nullable = false)
	public int getIdTransportista() {
		return this.idTransportista;
	}

	public void setIdTransportista(int idTransportista) {
		this.idTransportista = idTransportista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPersona", unique = true, nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "catLicencia", length = 5)
	public String getCatLicencia() {
		return this.catLicencia;
	}

	public void setCatLicencia(String catLicencia) {
		this.catLicencia = catLicencia;
	}

	@Column(name = "idSituacionTransportista")
	public Integer getIdSituacionTransportista() {
		return this.idSituacionTransportista;
	}

	public void setIdSituacionTransportista(Integer idSituacionTransportista) {
		this.idSituacionTransportista = idSituacionTransportista;
	}

	@Column(name = "nroLicencia", nullable = false, length = 15)
	public String getNroLicencia() {
		return this.nroLicencia;
	}

	public void setNroLicencia(String nroLicencia) {
		this.nroLicencia = nroLicencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportista")
	public List<Vehiculo> getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(List<Vehiculo> vehiculos) {
		this.vehiculos = vehiculos;
	}

}
