package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UbicacionHist generated by hbm2java
 */
@Entity
@Table(name="ubicacionHist"
    ,schema="dbo"
    ,catalog="HORADADA"
)
public class UbicacionHist  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idUbicacionhist;
     private String departamento;
     private String direccion;
     private Date fecha;
     private String hora;
     private Integer idUbicacion;
     private Integer idVehiculo;
     private String latitud;
     private String longitud;
     private String provincia;

    public UbicacionHist() {
    }

	
    public UbicacionHist(int idUbicacionhist) {
        this.idUbicacionhist = idUbicacionhist;
    }
    public UbicacionHist(int idUbicacionhist, String departamento, String direccion, Date fecha, String hora, Integer idUbicacion, Integer idVehiculo, String latitud, String longitud, String provincia) {
       this.idUbicacionhist = idUbicacionhist;
       this.departamento = departamento;
       this.direccion = direccion;
       this.fecha = fecha;
       this.hora = hora;
       this.idUbicacion = idUbicacion;
       this.idVehiculo = idVehiculo;
       this.latitud = latitud;
       this.longitud = longitud;
       this.provincia = provincia;
    }
   
     @Id 

    
    @Column(name="idUbicacionhist", unique=true, nullable=false)
    public int getIdUbicacionhist() {
        return this.idUbicacionhist;
    }
    
    public void setIdUbicacionhist(int idUbicacionhist) {
        this.idUbicacionhist = idUbicacionhist;
    }

    
    @Column(name="departamento", length=15)
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="hora")
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }

    
    @Column(name="idUbicacion")
    public Integer getIdUbicacion() {
        return this.idUbicacion;
    }
    
    public void setIdUbicacion(Integer idUbicacion) {
        this.idUbicacion = idUbicacion;
    }

    
    @Column(name="idVehiculo")
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }

    
    @Column(name="latitud", length=20)
    public String getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="longitud", length=20)
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="provincia", length=15)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }




}


