package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioId generated by hbm2java
 */
@Embeddable
public class UsuarioId  implements java.io.Serializable {


     private long idusuario;
     private long idpersona;

    public UsuarioId() {
    }

    public UsuarioId(long idusuario, long idpersona) {
       this.idusuario = idusuario;
       this.idpersona = idpersona;
    }
   


    @Column(name="IDUSUARIO", nullable=false, precision=10, scale=0)
    public long getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(long idusuario) {
        this.idusuario = idusuario;
    }


    @Column(name="IDPERSONA", nullable=false, precision=10, scale=0)
    public long getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(long idpersona) {
        this.idpersona = idpersona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioId) ) return false;
		 UsuarioId castOther = ( UsuarioId ) other; 
         
		 return (this.getIdusuario()==castOther.getIdusuario())
 && (this.getIdpersona()==castOther.getIdpersona());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdusuario();
         result = 37 * result + (int) this.getIdpersona();
         return result;
   }   


}


