package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioId generated by hbm2java
 */
@Embeddable
public class UsuarioId  implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    private BigDecimal idpersona;
    private BigDecimal idusuario;

   public UsuarioId() {
   }

   public UsuarioId(BigDecimal idpersona, BigDecimal idusuario) {
      this.idpersona = idpersona;
      this.idusuario = idusuario;
   }
  


   @Column(name="IDPERSONA", nullable=false, scale=0)
   public BigDecimal getIdpersona() {
       return this.idpersona;
   }
   
   public void setIdpersona(BigDecimal idpersona) {
       this.idpersona = idpersona;
   }


   @Column(name="IDUSUARIO", nullable=false, scale=0)
   public BigDecimal getIdusuario() {
       return this.idusuario;
   }
   
   public void setIdusuario(BigDecimal idusuario) {
       this.idusuario = idusuario;
   }


  public boolean equals(Object other) {
        if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioId) ) return false;
		 UsuarioId castOther = ( UsuarioId ) other; 
        
		 return ( (this.getIdpersona()==castOther.getIdpersona()) || ( this.getIdpersona()!=null && castOther.getIdpersona()!=null && this.getIdpersona().equals(castOther.getIdpersona()) ) )
&& ( (this.getIdusuario()==castOther.getIdusuario()) || ( this.getIdusuario()!=null && castOther.getIdusuario()!=null && this.getIdusuario().equals(castOther.getIdusuario()) ) );
  }
  
  public int hashCode() {
        int result = 17;
        
        result = 37 * result + ( getIdpersona() == null ? 0 : this.getIdpersona().hashCode() );
        result = 37 * result + ( getIdusuario() == null ? 0 : this.getIdusuario().hashCode() );
        return result;
  }   


}


