package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="USUARIO"
    ,schema="HORADADA"
)
public class Usuario  implements java.io.Serializable {


     private UsuarioId id;
     private Persona persona;
     private String usuario;
     private String contrasena;
     private String fechaupdate;
     private Integer estado;

    public Usuario() {
    }

	
    public Usuario(UsuarioId id, Persona persona) {
        this.id = id;
        this.persona = persona;
    }
    public Usuario(UsuarioId id, Persona persona, String usuario, String contrasena, String fechaupdate, Integer estado) {
       this.id = id;
       this.persona = persona;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.fechaupdate = fechaupdate;
       this.estado = estado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idusuario", column=@Column(name="IDUSUARIO", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="idpersona", column=@Column(name="IDPERSONA", nullable=false, precision=10, scale=0) ) } )
    public UsuarioId getId() {
        return this.id;
    }
    
    public void setId(UsuarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDPERSONA", nullable=false, insertable=false, updatable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="USUARIO", length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="CONTRASENA", length=60)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    
    @Column(name="FECHAUPDATE", length=20)
    public String getFechaupdate() {
        return this.fechaupdate;
    }
    
    public void setFechaupdate(String fechaupdate) {
        this.fechaupdate = fechaupdate;
    }

    
    @Column(name="ESTADO", precision=5, scale=0)
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


