package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "dbo", catalog = "HORADADA")
public class Usuario implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private String nombreUsuario;
	private Persona persona;
	private String contrasena;
	private Boolean estado;
	private Date fechaUpdate;
	private List<RoleUsuario> roleUsuarios;

	public Usuario() {
	}

	public Usuario(String nombreUsuario, Persona persona) {
		this.nombreUsuario = nombreUsuario;
		this.persona = persona;
	}

	public Usuario(String nombreUsuario, Persona persona, String contrasena, Boolean estado, Date fechaUpdate,
			List<RoleUsuario> roleUsuarios) {
		this.nombreUsuario = nombreUsuario;
		this.persona = persona;
		this.contrasena = contrasena;
		this.estado = estado;
		this.fechaUpdate = fechaUpdate;
		this.roleUsuarios = roleUsuarios;
	}

	@Id

	@Column(name = "nombreUsuario", unique = true, nullable = false, length = 45)
	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPersona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "contrasena", length = 60)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaUpdate", length = 10)
	public Date getFechaUpdate() {
		return this.fechaUpdate;
	}

	public void setFechaUpdate(Date fechaUpdate) {
		this.fechaUpdate = fechaUpdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public List<RoleUsuario> getRoleUsuarios() {
		return this.roleUsuarios;
	}

	public void setRoleUsuarios(List<RoleUsuario> roleUsuarios) {
		this.roleUsuarios = roleUsuarios;
	}

}
