package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Valorizacion generated by hbm2java
 */
@Entity
@Table(name = "valorizacion", schema = "dbo", catalog = "HORADADA")
public class Valorizacion implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private int idValorizacion;
	private Cliente cliente;
	private Date fecha;
	private Short idMoneda;
	private BigDecimal igv;
	private String observaciones;
	private BigDecimal subTotal;
	private BigDecimal total;
	private List<ValorizacionDetalle> valorizacionDetalles;

	public Valorizacion() {
	}

	public Valorizacion(int idValorizacion) {
		this.idValorizacion = idValorizacion;
	}

	public Valorizacion(int idValorizacion, Cliente cliente, Date fecha, Short idMoneda, BigDecimal igv,
			String observaciones, BigDecimal subTotal, BigDecimal total, List<ValorizacionDetalle> valorizacionDetalles) {
		this.idValorizacion = idValorizacion;
		this.cliente = cliente;
		this.fecha = fecha;
		this.idMoneda = idMoneda;
		this.igv = igv;
		this.observaciones = observaciones;
		this.subTotal = subTotal;
		this.total = total;
		this.valorizacionDetalles = valorizacionDetalles;
	}

	@Id

	@Column(name = "idValorizacion", unique = true, nullable = false)
	public int getIdValorizacion() {
		return this.idValorizacion;
	}

	public void setIdValorizacion(int idValorizacion) {
		this.idValorizacion = idValorizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCliente")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "idMoneda")
	public Short getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(Short idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "igv", precision = 12)
	public BigDecimal getIgv() {
		return this.igv;
	}

	public void setIgv(BigDecimal igv) {
		this.igv = igv;
	}

	@Column(name = "observaciones", length = 150)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "subTotal", precision = 12)
	public BigDecimal getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(BigDecimal subTotal) {
		this.subTotal = subTotal;
	}

	@Column(name = "total", precision = 12)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "valorizacion")
	public List<ValorizacionDetalle> getValorizacionDetalles() {
		return this.valorizacionDetalles;
	}

	public void setValorizacionDetalles(List<ValorizacionDetalle> valorizacionDetalles) {
		this.valorizacionDetalles = valorizacionDetalles;
	}

}
