package com.projecto.Horadada.Entity;
// Generated 02-mar-2018 16:56:03 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Valorizacion generated by hbm2java
 */
@Entity
@Table(name="VALORIZACION"
    ,schema="HORADADA"
)
public class Valorizacion  implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
     private int idvalorizacion;
     private Cliente cliente;
     private Date fecha;
     private String observaciones;
     private BigDecimal subtotal;
     private BigDecimal igv;
     private BigDecimal total;
     private Byte idmoneda;
     private Set<Valorizaciondetalle> valorizaciondetalles = new HashSet<Valorizaciondetalle>(0);

    public Valorizacion() {
    }

	
    public Valorizacion(int idvalorizacion) {
        this.idvalorizacion = idvalorizacion;
    }
    public Valorizacion(int idvalorizacion, Cliente cliente, Date fecha, String observaciones, BigDecimal subtotal, BigDecimal igv, BigDecimal total, Byte idmoneda, Set<Valorizaciondetalle> valorizaciondetalles) {
       this.idvalorizacion = idvalorizacion;
       this.cliente = cliente;
       this.fecha = fecha;
       this.observaciones = observaciones;
       this.subtotal = subtotal;
       this.igv = igv;
       this.total = total;
       this.idmoneda = idmoneda;
       this.valorizaciondetalles = valorizaciondetalles;
    }
   
     @Id     
    @Column(name="IDVALORIZACION", unique=true, nullable=false, precision=5, scale=0)
    public int getIdvalorizacion() {
        return this.idvalorizacion;
    }
    
    public void setIdvalorizacion(int idvalorizacion) {
        this.idvalorizacion = idvalorizacion;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDCLIENTE")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @DateTimeFormat(pattern = "dd/MM/yyyy")
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="OBSERVACIONES", length=150)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="SUBTOTAL", precision=18)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="IGV", precision=18)
    public BigDecimal getIgv() {
        return this.igv;
    }
    
    public void setIgv(BigDecimal igv) {
        this.igv = igv;
    }

    
    @Column(name="TOTAL", precision=18)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    
    @Column(name="IDMONEDA", precision=2, scale=0)
    public Byte getIdmoneda() {
        return this.idmoneda;
    }
    
    public void setIdmoneda(Byte idmoneda) {
        this.idmoneda = idmoneda;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="valorizacion")
    public Set<Valorizaciondetalle> getValorizaciondetalles() {
        return this.valorizaciondetalles;
    }
    
    public void setValorizaciondetalles(Set<Valorizaciondetalle> valorizaciondetalles) {
        this.valorizaciondetalles = valorizaciondetalles;
    }




}


