package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ValorizacionDetalle generated by hbm2java
 */
@Entity
@Table(name="valorizacionDetalle"
    ,schema="dbo"
    ,catalog="HORADADA"
)
public class ValorizacionDetalle  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idValorizacionDetalle;
     private Despacho despacho;
     private Factura factura;
     private Valorizacion valorizacion;
     private BigDecimal costoStamby;
     private Short diasStamby;
     private Date fechaCarga;
     private Date fechaDescarga;
     private String guiaAnexada;
     private BigDecimal igv;
     private Integer item;
     private BigDecimal neto;
     private String nroGuiaTransporte;
     private BigDecimal subTotal;
     private BigDecimal total;

    public ValorizacionDetalle() {
    }

	
    public ValorizacionDetalle(int idValorizacionDetalle, Valorizacion valorizacion) {
        this.idValorizacionDetalle = idValorizacionDetalle;
        this.valorizacion = valorizacion;
    }
    public ValorizacionDetalle(int idValorizacionDetalle, Despacho despacho, Factura factura, Valorizacion valorizacion, BigDecimal costoStamby, Short diasStamby, Date fechaCarga, Date fechaDescarga, String guiaAnexada, BigDecimal igv, Integer item, BigDecimal neto, String nroGuiaTransporte, BigDecimal subTotal, BigDecimal total) {
       this.idValorizacionDetalle = idValorizacionDetalle;
       this.despacho = despacho;
       this.factura = factura;
       this.valorizacion = valorizacion;
       this.costoStamby = costoStamby;
       this.diasStamby = diasStamby;
       this.fechaCarga = fechaCarga;
       this.fechaDescarga = fechaDescarga;
       this.guiaAnexada = guiaAnexada;
       this.igv = igv;
       this.item = item;
       this.neto = neto;
       this.nroGuiaTransporte = nroGuiaTransporte;
       this.subTotal = subTotal;
       this.total = total;
    }
   
     @Id 

    
    @Column(name="idValorizacionDetalle", unique=true, nullable=false)
    public int getIdValorizacionDetalle() {
        return this.idValorizacionDetalle;
    }
    
    public void setIdValorizacionDetalle(int idValorizacionDetalle) {
        this.idValorizacionDetalle = idValorizacionDetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDespacho")
    public Despacho getDespacho() {
        return this.despacho;
    }
    
    public void setDespacho(Despacho despacho) {
        this.despacho = despacho;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idFactura")
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idValorizacion", nullable=false)
    public Valorizacion getValorizacion() {
        return this.valorizacion;
    }
    
    public void setValorizacion(Valorizacion valorizacion) {
        this.valorizacion = valorizacion;
    }

    
    @Column(name="costoStamby", precision=12)
    public BigDecimal getCostoStamby() {
        return this.costoStamby;
    }
    
    public void setCostoStamby(BigDecimal costoStamby) {
        this.costoStamby = costoStamby;
    }

    
    @Column(name="diasStamby")
    public Short getDiasStamby() {
        return this.diasStamby;
    }
    
    public void setDiasStamby(Short diasStamby) {
        this.diasStamby = diasStamby;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaCarga", length=10)
    public Date getFechaCarga() {
        return this.fechaCarga;
    }
    
    public void setFechaCarga(Date fechaCarga) {
        this.fechaCarga = fechaCarga;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaDescarga", length=10)
    public Date getFechaDescarga() {
        return this.fechaDescarga;
    }
    
    public void setFechaDescarga(Date fechaDescarga) {
        this.fechaDescarga = fechaDescarga;
    }

    
    @Column(name="guiaAnexada", length=20)
    public String getGuiaAnexada() {
        return this.guiaAnexada;
    }
    
    public void setGuiaAnexada(String guiaAnexada) {
        this.guiaAnexada = guiaAnexada;
    }

    
    @Column(name="igv", precision=12)
    public BigDecimal getIgv() {
        return this.igv;
    }
    
    public void setIgv(BigDecimal igv) {
        this.igv = igv;
    }

    
    @Column(name="item")
    public Integer getItem() {
        return this.item;
    }
    
    public void setItem(Integer item) {
        this.item = item;
    }

    
    @Column(name="neto", precision=12)
    public BigDecimal getNeto() {
        return this.neto;
    }
    
    public void setNeto(BigDecimal neto) {
        this.neto = neto;
    }

    
    @Column(name="nroGuiaTransporte", length=20)
    public String getNroGuiaTransporte() {
        return this.nroGuiaTransporte;
    }
    
    public void setNroGuiaTransporte(String nroGuiaTransporte) {
        this.nroGuiaTransporte = nroGuiaTransporte;
    }

    
    @Column(name="subTotal", precision=12)
    public BigDecimal getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(BigDecimal subTotal) {
        this.subTotal = subTotal;
    }

    
    @Column(name="total", precision=12)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }




}


