package com.projecto.Horadada.Entity;
// Generated 28/01/2020 04:40:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name = "vehiculo", schema = "dbo", catalog = "HORADADA")
public class Vehiculo implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private int idVehiculo;
	private Transportista transportista;
	private String color;
	private String detalles;
	private Date fechaUltimaRevision;
	private Integer idAseguradora;
	private Integer idMarca;
	private Integer idModelo;
	private Integer nroEjes;
	private BigDecimal pesoMaximo;
	private BigDecimal pesoVehiculo;
	private String placa;
	private String tarjetaCirculacion;
	private List<Ubicacion> ubicacions;

	public Vehiculo() {
	}

	public Vehiculo(int idVehiculo, Transportista transportista) {
		this.idVehiculo = idVehiculo;
		this.transportista = transportista;
	}

	public Vehiculo(int idVehiculo, Transportista transportista, String color, String detalles,
			Date fechaUltimaRevision, Integer idAseguradora, Integer idMarca, Integer idModelo, Integer nroEjes,
			BigDecimal pesoMaximo, BigDecimal pesoVehiculo, String placa, String tarjetaCirculacion, List<Ubicacion> ubicacions) {
		this.idVehiculo = idVehiculo;
		this.transportista = transportista;
		this.color = color;
		this.detalles = detalles;
		this.fechaUltimaRevision = fechaUltimaRevision;
		this.idAseguradora = idAseguradora;
		this.idMarca = idMarca;
		this.idModelo = idModelo;
		this.nroEjes = nroEjes;
		this.pesoMaximo = pesoMaximo;
		this.pesoVehiculo = pesoVehiculo;
		this.placa = placa;
		this.tarjetaCirculacion = tarjetaCirculacion;
		this.ubicacions = ubicacions;
	}

	@Id

	@Column(name = "idVehiculo", unique = true, nullable = false)
	public int getIdVehiculo() {
		return this.idVehiculo;
	}

	public void setIdVehiculo(int idVehiculo) {
		this.idVehiculo = idVehiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTransportista", nullable = false)
	public Transportista getTransportista() {
		return this.transportista;
	}

	public void setTransportista(Transportista transportista) {
		this.transportista = transportista;
	}

	@Column(name = "color", length = 15)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "detalles", length = 45)
	public String getDetalles() {
		return this.detalles;
	}

	public void setDetalles(String detalles) {
		this.detalles = detalles;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaUltimaRevision", length = 10)
	public Date getFechaUltimaRevision() {
		return this.fechaUltimaRevision;
	}

	public void setFechaUltimaRevision(Date fechaUltimaRevision) {
		this.fechaUltimaRevision = fechaUltimaRevision;
	}

	@Column(name = "idAseguradora")
	public Integer getIdAseguradora() {
		return this.idAseguradora;
	}

	public void setIdAseguradora(Integer idAseguradora) {
		this.idAseguradora = idAseguradora;
	}

	@Column(name = "idMarca")
	public Integer getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(Integer idMarca) {
		this.idMarca = idMarca;
	}

	@Column(name = "idModelo")
	public Integer getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(Integer idModelo) {
		this.idModelo = idModelo;
	}

	@Column(name = "nroEjes")
	public Integer getNroEjes() {
		return this.nroEjes;
	}

	public void setNroEjes(Integer nroEjes) {
		this.nroEjes = nroEjes;
	}

	@Column(name = "pesoMaximo", precision = 6)
	public BigDecimal getPesoMaximo() {
		return this.pesoMaximo;
	}

	public void setPesoMaximo(BigDecimal pesoMaximo) {
		this.pesoMaximo = pesoMaximo;
	}

	@Column(name = "pesoVehiculo", precision = 6)
	public BigDecimal getPesoVehiculo() {
		return this.pesoVehiculo;
	}

	public void setPesoVehiculo(BigDecimal pesoVehiculo) {
		this.pesoVehiculo = pesoVehiculo;
	}

	@Column(name = "placa", length = 7)
	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	@Column(name = "tarjetaCirculacion", length = 15)
	public String getTarjetaCirculacion() {
		return this.tarjetaCirculacion;
	}

	public void setTarjetaCirculacion(String tarjetaCirculacion) {
		this.tarjetaCirculacion = tarjetaCirculacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculo")
	public List<Ubicacion> getUbicacions() {
		return this.ubicacions;
	}

	public void setUbicacions(List<Ubicacion> ubicacions) {
		this.ubicacions = ubicacions;
	}

}
